name: build 🏗️

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [develop, staging, main]

  workflow_dispatch:

jobs:
  build_code:
    name: run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Enable corepack
        run: |
          corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: build
        run: |
          yarn install
          yarn build
